'
' NOTE : Generated file. Do not edit. Your changes may be lost on the next update!
'        Generated by g2bmx on 10 Mar 2020
'
Strict

Module GLFW.GLFWOpenGL

ModuleInfo "Version: 1.00"
ModuleInfo "Author: Milan Ikits, Marcelo Magallon"
ModuleInfo "License: SGI Free Software License B"
ModuleInfo "Copyright: Milan Ikits, Marcelo Magallon"

ModuleInfo "History: 1.00"
ModuleInfo "History: Initial version."

Import "../glfw.mod/glfw/deps/*.h"

Import "opengl.bmx"
Import "glad00.bmx"

